### ISSUE TITLE
When Google ad is completed, black screen

### ISSUE THREAD

**Issue by ANIKINKIRILL** [LimeHD/adsmodule#1]

**Comment by ANIKINKIRILL** [comment]
При завершении гугл рекламы. Плеер остаётся кликабельным, но сама передача, которая сейчас идёт, не играет

**Comment by ANIKINKIRILL** [comment]
Также когда переключаю качество видео (с low на mid), то передача начинает играть

**Comment by powerewop** [comment]
еще актуально?

**Comment by powerewop** [comment]
этот функционал не относится к работе модуля. модуль должен обеспечить колбэками приложение для корректной работы последнего
